# Generated by Django 3.2.4 on 2024-03-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('authoredDate', models.DateTimeField(auto_now_add=True)),
                ('seenDate', models.DateTimeField(blank=True, null=True)),
                ('readed', models.BooleanField(default=False)),
                ('readBy', models.CharField(blank=True, max_length=50, null=True)),
                ('authorizedTo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ReplyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('repliedBy', models.CharField(max_length=50)),
                ('repliedDate', models.DateTimeField(auto_now_add=True)),
                ('replyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagetable')),
            ],
            options={
                'verbose_name_plural': 'replies',
            },
        ),
    ]
