# Generated by Django 3.2.4 on 2024-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytable',
            name='main_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
