# Generated by Django 3.2.4 on 2024-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_replytable_main_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetable',
            name='receivedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
