# Generated by Django 3.2.4 on 2024-04-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagetable_receiveddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('repliedBy', models.CharField(max_length=50)),
                ('repliedDate', models.DateTimeField(auto_now_add=True)),
                ('main_message', models.TextField()),
                ('replyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.replytable')),
            ],
        ),
    ]
