# Generated by Django 3.2.4 on 2024-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_mainmessagereply'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_message', models.TextField()),
                ('main_message_id', models.IntegerField()),
                ('Replies', models.JSONField(default=False, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainmessagereply',
            options={'verbose_name_plural': 'authorReplies'},
        ),
        migrations.AddField(
            model_name='mainmessagereply',
            name='reply_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replytable',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
